import '@/styles/globals.css';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Plus_Jakarta_Sans } from 'next/font/google';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '@/trpc/react';
import { Toaster } from './_components/ui/sonner';
import { SessionProvider } from 'next-auth/react';
import ThemeProvider from '@/app/_components/theme-provider';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-jakarta',
  weight: ['400', '500', '600', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${jakarta.variable}`}
      suppressHydrationWarning
    >
      <body>
        <TRPCReactProvider>
          <SessionProvider>
            <NuqsAdapter>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </NuqsAdapter>
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
